name: بلاغ عطل / Bug Report
description: صف المشكلة أو العطل الذي واجهته في لعبة NFS Cinematic Edition
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        يرجى تعبئة التفاصيل التالية لتسريع إصلاح المشكلة.
  - type: dropdown
    id: priority
    attributes:
      label: الأولوية / Priority
      options:
        - High
        - Medium
        - Low
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: الوصف / Description
      description: صف ما حدث بالتفصيل.
      placeholder: عند الدعس على الكلب تتجمد اللعبة...
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: خطوات إعادة المشكلة / Steps to Reproduce
      description: اذكر الخطوات التي تؤدي لظهور المشكلة.
      placeholder: |
        1. افتح اللعبة
        2. اضغط ...
        3. لاحظ النتيجة
  - type: textarea
    id: expected
    attributes:
      label: النتيجة المتوقعة / Expected Behavior
  - type: textarea
    id: environment
    attributes:
      label: البيئة / Environment
      description: المتصفح والجهاز (مثال: iPhone iOS 17 - Safari)
  - type: textarea
    id: console
    attributes:
      label: Console Log
      description: الصق أي رسائل من Console.
  - type: textarea
    id: media
    attributes:
      label: صور أو فيديو / Evidence
      description: أرفق لقطات شاشة أو فيديو إن أمكن.
  - type: textarea
    id: additional
    attributes:
      label: ملاحظات إضافية / Additional Notes
