name: طلب ميزة / Feature Request
description: اقترح تحسينًا أو ميزة جديدة
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ما الفكرة الجديدة التي تود إضافتها للعبة؟
  - type: textarea
    id: summary
    attributes:
      label: الوصف / Summary
      description: ما الميزة التي تقترحها؟
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: السبب / Motivation
      description: لماذا هذه الميزة مهمة؟
  - type: textarea
    id: acceptance
    attributes:
      label: معايير القبول / Acceptance Criteria
      description: كيف نعرف أن الميزة أُنجزت بنجاح؟
  - type: textarea
    id: additional
    attributes:
      label: تفاصيل إضافية / Additional Details
