export const ArtKeys = {
  BG_SKY: 'bg_sky',
  DUNE_FAR: 'dune_far',
  DUNE_MID: 'dune_mid',
  DUNE_NEAR: 'dune_near',
  GROUND_ROAD: 'ground_road',
  GROUND_DUNES: 'ground_dunes',
  POI_STATION: 'poi_station',
  POI_SHOP: 'poi_shop',
  POI_RESTAURANT: 'poi_restaurant',
  ICON_SALT: 'icon_salt',
  ICON_WATER: 'icon_water',
  ICON_CHARCOAL: 'icon_charcoal',
  ICON_LIGHTER: 'icon_lighter',
  ICON_HUMMUS: 'icon_hummus',
  VEH_GMC: 'veh_gmc',
  VEH_PRADO: 'veh_prado',
  VEH_SHADOW: 'veh_shadow',
  HELICOPTER: 'event_helicopter',
  CAMEL: 'event_camel',
  DOG: 'event_dog',
  PUFF: 'puff',
  FINISH_FLAG: 'finish_flag'
} as const;
